export const jamNameList = [
  '18										',
  'Guardian                               ',
  'Construction/destruction (sheep)       ',
  'Preparation – Set it up, let it go     ',
  'Infection                              ',
  'Random                                 ',
  'Light and darkness                     ',
  'Growth                                 ',
  'Swarms                                 ',
  'Moon/anti-text                         ',
  'Build the level you play               ',
  'Chain reaction                         ',
  'Weird/unexpected/surprise              ',
  'Minimalist                             ',
  'The tower                              ',
  'Roads                                  ',
  'Advancing wall of doom                 ',
  'Caverns                                ',
  'Exploration                            ',
  'Islands                                ',
  'Enemies as weapons                     ',
  'Discovery                              ',
  'It’s dangerous to go alone! Take this! ',
  'Escape                                 ',
  'Alone (kitten challenge)               ',
  'Tiny world                             ',
  'Evolution                              ',
  'You are the villain (goat)             ',
  'Minimalism (potato)                    ',
  '10 seconds                             ',
  'You only get one                       ',
  'Beneath the surface                    ',
  'Connected Worlds                       ',
  'Entire Game on One Screen              ',
  'An Unconventional Weapon               ',
  'You are the Monster                    ',
  'Growing/two button controls            ',
  'Shapeshift                             ',
  'Ancient Technology                     ',
  'One Room                               ',
  'A Small World                          ',
  'Running out of Power                   ',
  'The more you have, the worse it is     ',
  'Combine two incompatible genres        ',
  'Running out of space                   ',
  'Sacrifices must be made                ',
  'Your life is currency                  ',
  "I Put a Spell on You							",
  "The Working Man                                  ",
  "Ninety-Nine and a Half                           ",
  "Gloomy                                           ",
  "Good Times Bad Times                             ",
  "Babe I'm Gonna Leave You                         ",
  "You Shook Me                                     ",
  "Dazed And Confused                               ",
  "Your Time Is Gonna Come                          ",
  "Communication Breakdown                          ",
  "I Can't Quit You Babe                            ",
  "How Many More Times                              ",
  "Whole Lotta Love                                 ",
  "What Is And What Should Never Be                 ",
  "The Lemon Song                                   ",
  "Thank You                                        ",
  "Heartbreaker                                     ",
  "Ramble On                                        ",
  "Moby Dick                                        ",
  "Bring It On Home                                 ",
  "Immigrant Song                                   ",
  "Friends                                          ",
  "Celebration Day                                  ",
  "Since I've Been Loving You                       ",
  "Out On The Tiles                                 ",
  "Gallows Pole                                     ",
  "Tangerine                                        ",
  "That's The Way                                   ",
  "Hats Off                                         ",
  "Black Dog                                        ",
  "Rock And Roll                                    ",
  "The Battle Of Evermore                           ",
  "Stairway To Heaven                               ",
  "Misty Mountain Hop                               ",
  "Four Sticks                                      ",
  "Going To California                              ",
  "When The Levee Breaks                            ",
  "The Song Remains the Same                        ",
  "The Rain Song                                    ",
  "Over the Hills and Far Away                      ",
  "The Crunge                                       ",
  "Dancing Days                                     ",
  "Feelin hot hot hot                               ",
  "No Quarter                                       ",
  "The Ocean                                        ",
  "Pies                                             ",
  "In My Time Of Dying                              ",
  "Houses Of The Holy                               ",
  "Trampled Underfoot                               ",
  "In the Light                                     ",
  "Down by the Seaside                              ",
  "Ten Years Gone                                   ",
  "Night Flight                                     ",
  "The Wanton Song                                  ",
  "Pixel Boogie                                     ",
  "Black Country Woman                              ",
  "Sick Again                                       ",
  "Rock And Roll                                    ",
  "Celebration Day                                  ",
  "Black Dog                                        ",
  "Over The Hills And Far Away                      ",
  "Misty Mountain Hop                               ",
  "Since I've Been Loving You                       ",
  "No Quarter                                       ",
  "The Song Remains The Same                        ",
  "The Rain Song                                    ",
  "The Ocean                                        ",
  "Dazed And Confused                               ",
  "Stairway To Heaven                               ",
  "Moby Dick                                        ",
  "Heartbreaker                                     ",
  "Whole Lotta Love                                 ",
  "Achilles Last Stand                              ",
  "For Your Life                                    ",
  "Royal Orleans                                    ",
  "Nobody's Fault But Mine                          ",
  "Candy Store Rock                                 ",
  "Hots On For Nowhere                              ",
  "Tea For One                                      ",
  "In The Evening                                   ",
  "South Bound Saurez                               ",
  "Fool In The Rain                                 ",
  "Hot Dog                                          ",
  "Carouselambra                                    ",
  "All My Love                                      ",
  "I'm Gonna Crawl                                  ",
  "We're Gonna Groove                               ",
  "Poor Tom                                         ",
  "I Can't Quit You Baby                            ",
  "Walter's Walk                                    ",
  "Ozone Baby                                       ",
  "Darlene                                          ",
  "Bonzo's Montreux                                 ",
  "Wearing And Tearing                              ",
  "You Shook Me                                     ",
  "I Can't Quit You Baby                            ",
  "Communication Breakdown                          ",
  "Dazed and Confused                               ",
  "The Girl I Love She Got Long Black Wavy Hair     ",
  "What Is and What Should Never Be                 ",
  "Communication Breakdown                          ",
  "Travelling Riverside Blues                       ",
  "Whole Lotta Love                                 ",
  "Somethin' Else                                   ",
  "Communication Breakdown                          ",
  "I Can't Quit You Baby                            ",
  "You Shook Me                                     ",
  "How Many More Times                              ",
  "Heartbreaker                                     ",
  "Black Dog                                        ",
  "Over The Hills And Far Away                      ",
  "Since I've Been Loving You                       ",
  "Stairway To Heaven                               ",
  "Going To California                              ",
  "That's The Way                                   ",
  "Bron-Yr-Aur Stomp                                ",
  "Dazed And Confused                               ",
  "What Is And What Should Never Be                 ",
  "Dancing Days                                     ",
  "Moby Dick                                        ",
  "Push It Along                                    ",
  "Luck Of Lucien                                   ",
  "After Hours                                      ",
  "Footprints                                       ",
  "I Left My Wallet In El Segundo                   ",
  "Public Enemy                                     ",
  "Bonita Applebum                                  ",
  "Can I Kick It?                                   ",
  "Youthful Expression                              ",
  "Rhythm (Devoted To The Art Of Moving Butts)      ",
  "Ham 'n' Eggs                                     ",
  "Go Ahead In The Rain                             ",
  "Description Of A Fool                            ",
  "Can I Kick It?                                   ",
  "Excursions                                       ",
  "Buggin' Out                                      ",
  "Rap Promoter                                     ",
  "Butter                                           ",
  "Verses From The Abstract                         ",
  "Show Business                                    ",
  "Vibes Anf Stuff                                  ",
  "The Infamous Date Rape                           ",
  "Check The Rhime                                  ",
  "Everything Is Fair                               ",
  "What?                                            ",
  "Scenario                                         ",
  "Midnight Marauders Tour Intro                    ",
  "Award Tour                                       ",
  "8 Million Stories                                ",
  "Midnight                                         ",
  "We Can Get Down                                  ",
  "Electric Relaxation                              ",
  "Clap Your Hands                                  ",
  "Oh My God                                        ",
  "Keep It Rollin'                                  ",
  "The Chase, Part Ii                               ",
  "Lyrics To Go                                     ",
  "God Lives Through                                ",
  "Electric Relaxation                              ",
  "Get A Hold                                       ",
  "Motivators                                       ",
  "Jam                                              ",
  "Crew                                             ",
  "Award Tour                                       ",
  "Can I Kick It                                    ",
  "One, Two, Shit                                   ",
  "Electric Relaxation                              ",
  "Mr. Incognito                                    ",
  "I Left My Wallet in El Segundo                   ",
  "Check the Rhime                                  ",
  "Lyrics to Go (Tumblin' Dice remix)               ",
  "Scenario                                         ",
  "Same Ol' Thing                                   ",
  "Buggin' Out                                      ",
  "Bonita Applebum                                  ",
  "Jazz (We've Got)                                 ",
  "Glamour & Glitz                                  ",
  "Clap Your Hands                                  ",
  "The Night He Got Caught                          ",
  "Peace, Prosperity & Paper                        ",
  "Whole Lotta Love                                 ",
  "Rock And Roll                                    ",
  "The Ocean                                        ",
  "Bring It On Home                                 ",
  "Good Times Bad Times                             ",
  "Ramble On                                        ",
  "Black Dog                                        ",
  "In My Time of Dying                              ",
  "For Your Life                                    ",
  "Trampled Under Foot                              ",
  "Nobody's Fault But Mine                          ",
  "No Quarter                                       ",
  "Since I've Been Loving You                       ",
  "Dazed And Confused                               ",
  "Stairway To Heaven                               ",
  "Song Remains The Same                            ",
  "Misty Mountain Hop                               ",
  "Kashmir                                          ",
  "Whole Lotta Love                                 ",
  "Rock And Roll                                    ",
  "Walk on the Water                                ",
  "Susie Q [Live]                                   ",
  "Born on the Bayou                                ",
  "Bootleg                                          ",
  "Graveyard Train                                  ",
  "Good Golly Miss Molly                            ",
  "Penthouse Pauper                                 ",
  "Proud Mary                                       ",
  "Green River                                      ",
  "Commotion                                        ",
  "Tombstone Shadow                                 ",
  "Wrote a Song for Everyone                        ",
  "Bad Moon Rising                                  ",
  "Lodi                                             ",
  "Cross-Tie Walker                                 ",
  "Sinister Purpose                                 ",
  "The Night Time Is the Right Time                 ",
  "Down on the Corner                               ",
  "It Came out of the Sky                           ",
  "Cotton Fields                                    ",
  "Poorboy Shuffle                                  ",
  "Feelin' Blue                                     ",
  "Fortunate Son                                    ",
  "Don't Look Now                                   ",
  "The Midnight Special                             ",
  "Side O' the Road                                 ",
  "Effigy                                           ",
  "It Came out of the Sky                           ",
  "Down on the Corner                               ",
  "Before You Accuse Me                             ",
  "Travelin' Band                                   ",
  "Ooby Dooby                                       ",
  "Lookin' out My Back Door                         ",
  "Run Through the Jungle                           ",
  "Up Around the Bend                               ",
  "My Baby Left Me                                  ",
  "Who'll Stop the Rain                             ",
  "I Heard It Through the Grapevine                 ",
  "Long as I Can See the Light                      ",
  "Pagan Baby                                       ",
  "Sailor's Lament                                  ",
  "Chameleon                                        ",
  "Have You Ever Seen The Rain                      ",
  "(I Wish I Could) Hideaway                        ",
  "Born To Move                                     ",
  "Hey Tonight                                      ",
  "It's Just A Thought                              ",
  "Rude Awakening #2                                ",
  "45 Revolutions Per Minute                        ",
  "Hey Tonight [Live][*]                            ",
  "Lookin' For a Reason                             ",
  "Take It Like A Friend                            ",
  "Need Someone To Hold                             ",
  "Tearin' Up The Country                           ",
  "Someday Never Comes                              ",
  "What Are You Gonna Do                            ",
  "Sail Away                                        ",
  "Hello Mary Lou                                   ",
  "Door to Door                                     ",
  "Sweet Hitch-Hiker                                ",
  "Born In The U.S.A.                               ",
  "Cover Me                                         ",
  "Darlington County                                ",
  "Working On The Highway                           ",
  "Downbound Train                                  ",
  "I'm On Fire                                      ",
  "No Surrender                                     ",
  "Bobby Jean                                       ",
  "I'm Goin' Down                                   ",
  "Glory Days                                       ",
  "Dancing In The Dark                              ",
  "My Hometown                                      ",
  "Thunder Road                                     ",
  "Tenth Avenue Freeze-Out                          ",
  "Night                                            ",
  "Backstreets                                      ",
  "Born To Run                                      ",
  "She's The One                                    ",
  "Meeting Across The River                         ",
  "Jungleland                                       ",
  "Badlands                                         ",
  "Adam Raised A Cain                               ",
  "Something In The Night                           ",
  "Candy's Room                                     ",
  "Racing In The Street                             ",
  "The Promised Land                                ",
  "Factory                                          ",
  "Streets Of Fire                                  ",
  "Prove It All Night                               ",
  "Darkness On The Edge Of Town                     ",
  "Blinded By the Light                             ",
  "Growin' Up                                       ",
  "Mary Queen of Arkansas                           ",
  "Does This Bus Stop at 82nd Street?               ",
  "Lost in the Flood                                ",
  "The Angel                                        ",
  "For You                                          ",
  "Spirit in the Night                              ",
  "It's Hard to Be a Saint in the City              ",
  "Human Touch                                      ",
  "Soul Driver                                      ",
  "57 Channels (And Nothin' On)                     ",
  "Cross My Heart                                   ",
  "Gloria's Eyes                                    ",
  "With Every Wish                                  ",
  "Roll Of The Dice                                 ",
  "Real World                                       ",
  "All Or Nothin' At All                            ",
  "Man's Job                                        ",
  "I Wish I Were Blind                              ",
  "The Long Goodbye                                 ",
  "Real Man                                         ",
  "Pony Boy                                         ",
  "The Ties That Bind                               ",
  "Sherry Darling                                   ",
  "Jackson Cage                                     ",
  "Two Hearts                                       ",
  "Independence Day                                 ",
  "Hungry Heart                                     ",
  "Out In The Street                                ",
  "Crush On You                                     ",
  "You Can Look (But You Better Not Touch)          ",
  "I Wanna Marry You                                ",
  "The River                                        ",
  "Point Blank                                      ",
  "Cadillac Ranch                                   ",
  "I'm A Rocker                                     ",
  "Fade Away                                        ",
  "Stolen Car                                       ",
  "Ramrod                                           ",
  "The Price You Pay                                ",
  "Drive All Night                                  ",
  "Wreck On The Highway                             ",
  "The E Street Shuffle                             ",
  "4th of July, Asbury Park (Sandy)                 ",
  "Kitty's Back                                     ",
  "Wild Billy's Circus Story                        ",
  "Incident on 57th Street                          ",
  "Rosalita (Come Out Tonight)                      ",
  "New York City Serenade                           ",
  "Ain't Got You                                    ",
  "Tougher Than The Rest                            ",
  "All That Heaven Will Allow                       ",
  "Spare Parts                                      ",
  "Cautious Man                                     ",
  "Walk Like A Man                                  ",
  "Tunnel Of Love                                   ",
  "Two Faces                                        ",
  "Brilliant Disguise                               ",
  "One Step Up                                      ",
  "When You're Alone                                ",
  "Valentine's Day                                  ",
]