export const jamNameList = [
  'Guardian                               ',
  'Construction/destruction        ',
  'Preparation – Set it up, let it go     ',
  'Infection                              ',
  'Random                                 ',
  'Light and darkness                     ',
  'Growth                                 ',
  'Swarms                                 ',
  'Moon/anti-text                         ',
  'Build the level you play               ',
  'Chain reaction                         ',
  'Weird/unexpected/surprise              ',
  'Minimalist                             ',
  'The tower                              ',
  'Roads                                  ',
  'Advancing wall of doom                 ',
  'Caverns                                ',
  'Exploration                            ',
  'Islands                                ',
  'Enemies as weapons                     ',
  'Discovery                              ',
  'It’s dangerous to go alone! Take this! ',
  'Escape                                 ',
  'Alone (kitten challenge)               ',
  'Tiny world                             ',
  'Evolution                              ',
  'You are the villain (goat)             ',
  'Minimalism (potato)                    ',
  '10 seconds                             ',
  'You only get one                       ',
  'Beneath the surface                    ',
  'Connected Worlds                       ',
  'Entire Game on One Screen              ',
  'An Unconventional Weapon               ',
  'You are the Monster                    ',
  'Growing/two button controls            ',
  'Shapeshift                             ',
  'Ancient Technology                     ',
  'One Room                               ',
  'A Small World                          ',
  'Running out of Power                   ',
  'The more you have, the worse it is     ',
  'Combine two incompatible genres        ',
  'Running out of space                   ',
  'Sacrifices must be made                ',
  'Your life is currency                  ',
  "I Put a Spell on You							",
  "The Working Man                                  ",
  "Ninety-Nine and a Half                           ",
  "Gloomy                                           ",
  "Good Times Bad Times                             ",
  "You Shook Me                                     ",
  "Dazed And Confused                               ",
  "Your Time Is Gonna Come                          ",
  "Communication Breakdown                          ",
  "I Can't Quit You Babe                            ",
  "How Many More Times                              ",
  "What Is And What Should Never Be                 ",
  "Thank You                                        ",
  "Ramble On                                        ",
  "Moby Dick                                        ",
  "Bring It On Home                                 ",
  "Friends                                          ",
  "Celebration Day                                  ",
  "Since I've Been Loving You                       ",
  "Out On The Tiles                                 ",
  "Gallows Pole                                     ",
  "That's The Way                                   ",
  "Hats Off                                         ",
  "Black Dog                                        ",
  "Rock And Roll                                    ",
  "Misty Mountain Hop                               ",
  "Four Sticks                                      ",
  "Going To California                              ",
  "When The Levee Breaks                            ",
  "The Song Remains the Same                        ",
  "The Rain Song                                    ",
  "Over the Hills and Far Away                      ",
  "The Crunge                                       ",
  "Dancing Days                                     ",
  "Feelin hot hot hot                               ",
  "No Quarter                                       ",
  "The Ocean                                        ",
  "Pies                                             ",
  "In My Time Of Dying                              ",
  "Houses Of The Holy                               ",
  "In the Light                                     ",
  "Push It Along                                    ",
  "Luck                                   ",
  "After Hours                                      ",
  "Footprints                                       ",
  "Public Enemy                                     ",
  "Can I Kick It?                                   ",
  "Can I Kick It?                                   ",
  "Excursions                                       ",
  "Show Business                                    ",
  "Vibes Anf Stuff                                  ",
  "Check The Rhime                                  ",
  "Everything Is Fair                               ",
  "What?                                            ",
  "Scenario                                         ",
  "8 Million Stories                                ",
  "Midnight                                         ",
  "Electric Relaxation                              ",
  "Sinister Purpose                                 ",
  "The Night Time Is the Right Time                 ",
  "Down on the Corner                               ",
  "It Came out of the Sky                           ",
  "Cotton Fields                                    ",
  "Feelin' Blue                                     ",
  "The Midnight Special                             ",
  "Effigy                                           ",
  "I'm Goin' Down                                   ",
  "Glory Days                                       ",
  "Dancing In The Dark                              ",
  "Night                                            ",
  "Backstreets                                      ",
  "Jungleland                                       ",
  "Badlands                                         ",
  "Something In The Night                           ",
  "The Promised Land                                ",
  "Factory                                          ",
  "Streets Of Fire                                  ",
  "Blinded By the Light                             ",
  "When You're Alone                                ",
]